os: linux
sudo: false
language: python
python: 3.6
env: TOXENV=normal-hypothesis,codecov

matrix:
  include:
    - python: 3.6
      env: TOXENV=normal-hypothesis,codecov
    - python: 3.5
      env: TOXENV=normal,codecov
    - python: 3.4
      env: TOXENV=normal,codecov
    - python: 3.3
      env: TOXENV=normal,codecov
    - python: 2.7
      env: TOXENV=normal,codecov
    - python: 2.6
      env: TOXENV=normal,codecov
    - python: pypy
      env: TOXENV=pypy-normal,codecov
    - python: nightly
      env: TOXENV=normal
    - python: 3.6
      env: TOXENV=uwsgi,codecov
    - python: 3.6
      env: TOXENV=stylecheck
    - python: 3.6
      env: TOXENV=docs-html
    - os: osx
      language: generic
      env: TOXENV=normal
  allow_failures:
    - os: osx
      language: generic
      env: TOXENV=normal
  fast_finish: true

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew install python3 redis memcached;
        virtualenv -p python3 ~/py-env;
        . ~/py-env/bin/activate;
      fi
    # Travis uses an outdated PyPy, this installs a more recent one.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "pypy" ]]; then
        git clone https://github.com/pyenv/pyenv.git ~/.pyenv;
        PYENV_ROOT="$HOME/.pyenv";
        PATH="$PYENV_ROOT/bin:$PATH";
        eval "$(pyenv init -)";
        pyenv install pypy2.7-5.8.0;
        pyenv global pypy2.7-5.8.0;
      fi
    - if [[ "$TRAVIS_PYTHON_VERSION" == "pypy3" ]]; then
        git clone https://github.com/pyenv/pyenv.git ~/.pyenv;
        PYENV_ROOT="$HOME/.pyenv";
        PATH="$PYENV_ROOT/bin:$PATH";
        eval "$(pyenv init -)";
        pyenv install pypy3.5-5.8.0;
        pyenv global pypy3.5-5.8.0;
      fi

install:
  - pip install tox

script:
  - tox

cache:
  - pip

branches:
  only:
    - master
    - auto
    - /^.*-maintenance$/

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
